app = "whatsapp-proxy"

primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true

[[services]]
  http_checks = []
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443